name: Generate PDF from C Programs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y enscript ghostscript

    - name: Set execute permissions
      run: chmod +x generate_pdf.sh

    - name: Remove old PDF
      run: |
        if [ -f programs.pdf ]; then
          rm programs.pdf
        fi

    - name: Generate PDF
      run: |
        find ./TPEC/M1 ./TPEC/M2 ./TPEC/M3 -name '*.c' -exec enscript {} -o - \; > output.ps
        ps2pdf output.ps programs.pdf
        rm output.ps

    - name: Stash uncommitted changes
      run: git stash || echo "No changes to stash"

    - name: Commit and push PDF
      env:
        GITHUB_TOKEN: ${{ secrets.pdf_runner }}
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        git pull origin main --rebase  # Pull latest changes
        git add programs.pdf
        git commit -m "Update PDF with latest C programs" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/Anorak001/Dump.git HEAD:main
