name: Generate PDF from C Programs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y enscript ghostscript

    - name: Set execute permissions
      run: chmod +x generate_pdf.sh

    - name: Generate PDF
      run: ./generate_pdf.sh

    - name: Commit and push PDF
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        git add programs.pdf
        git commit -m "Update PDF with latest C programs"
        git push
